# k8s/base/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: docker-registry-auth
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:wwi825LqcKNJfOsFL0lAMrRUyzdJ6vAbAXSQy9nsFtPMCDL3pSzxgVFQ1WQ5aftReCoJnxx+uMCYxTZiuihy0bVX6Wbd7YcTE8ZB7cwwtPnVEAsJrrxShtUq1dmhCeSzLend+Q9tjmf49oGbE8vq54tL3H0LfExCktJagkt2RKdc1HNYI/g97j6sKoNV64kNdrVbE5usjRR7LGNNF7vRZkbZ3jSAcgTyPoTIi8VZfXKvi4gBTI7KCEetqg/OgLnCBUoqUQmgJL5DH+xHFvEx9Xrhgjd0NL18r6z5lJXbtQ==,iv:iHqFpb5hvE9eXIFDDVaR9vaToLuLuHzFESr2myZAbgQ=,tag:HMO07Ig8QOb1agMW8H6Ccw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/silicon-works-449817-n7/locations/us/keyRings/csye7125/cryptoKeys/sops
          created_at: "2025-03-04T01:48:21Z"
          enc: CiQA7TLpiOnCH329pZ63W51mtV4iJGw4GGjQmcweytO4lbbicgwSSQB/iRXt8+SKuXVC/JxwkU5x2QdcvcNSWZCQYjHr91W9WXbv2eqJJvvEkjRGqvoO+SuKmbOslx1AoObRa+RLGrnTBkT2rvVX6x4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-04T01:48:21Z"
    mac: ENC[AES256_GCM,data:DPviE8suTuw+fasR1pdbNzBuw20WBXavV5hGe9w7bZCHOV16N1b4yjHeBqZp5gKrHVWaaaIi+O6KAZdTu2HwXdLUlggQJUfsdW4GhkmHkM42rRqe2+ohXVUExincReS0CaunREjgcNsPKHcP7RKdast8QLE6uPPf8yQICktJMH8=,iv:LTmtOS6z6hs3TOAJjjgaeYuO2LXNhNLonuh7U5+KFf0=,tag:kmj9kQL2KJakkXJ8eO33Vg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
