apiVersion: ENC[AES256_GCM,data:pJc=,iv:6ZpPfuT0K4TVc5oSDoZBzqM7JF770zVJVY4JbIZhbkE=,tag:DKONCFyt84rvBBNMigVTAg==,type:str]
kind: ENC[AES256_GCM,data:5uILH76k,iv:D4SVCr9bok1Sl+Q+C4LuVgjuW8qbgEvh+XlLoY8rlvU=,tag:/pvQCGWdxTcphHPNVt56Qw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:lXR38kLjxWtVdX0zsVujhigdl8k=,iv:z5b7Pr848GprNfXMPk3UV7+3YYI3Sg9g6wAgFB29tNg=,tag:ILl27WFJkQvVCQOwdFsPrA==,type:str]
type: ENC[AES256_GCM,data:0fVE2CEA,iv:mKM2tqwbTKXgnvLF27B1UN+zNLhP4J8IE+AFzG+4dpQ=,tag:FOT4+qeMOEGDAgxKJ6PDzA==,type:str]
stringData:
  DB_HOST: ENC[AES256_GCM,data:WM7ViVh4IGjiiFV7,iv:dryp8WcxdlsW/Uhz51+syIsa/MDE8eMXwS7/9r+zmkc=,tag:+CH2lDJU2XvF+OBRtFEwKA==,type:str]
  DB_USER: ENC[AES256_GCM,data:FyUjW7wt6sk=,iv:ZGjelcz6MZEFnLP8DWERMoBInN/rxUJnn98m+ZWvRbE=,tag:AjCgBnJMFJX1GfK9ghlYRw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:trHyhKbd/Hxh8OFJJG3n2BA0t6M=,iv:R6D1Lzfp/75GI06mIUad8ifVp1qm0XtXVGXmY1iMva4=,tag:x4hfspS3tIrqnczSbCP0Jg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:6KUfouR3pRI=,iv:e/9OW9tJl5TI+iH20IM/yCj7U4Ava2UKOOzlh70D9Nw=,tag:02a4buOCdqs+lx9NpPcLrQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:qZ0f9xaSZdg=,iv:ONX3HQUboWWJ+1B+S3nAh5G26Pt9P3PHt+aSCK6jw5w=,tag:RQTHHKiXPcL+QHJ+r5HJPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18n3ez3s0z0e9cuncrnvunq3sdur8wgn4rqpd9dtcunmr9eg7tuvsu4k2jn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiay9aNTBxVnNFQmZNQ290
        dks2MmcvcjY5TEVocXUrVy9sQlJ1cDFHcG1nCjU3eTJ5a1lDVHdxZXkreDRYSFJp
        VTVSZzlxdHZFbDB5QmdrQi96SGtNMXcKLS0tIE5JQ2JSR1gwMlJPNVZPTTNjcFhD
        d25SQnQ2YlNQdHBHYVdtaTBaN3FNZjQKsRXcNE8Ee9F4gMyIsWDugMU9I1gv456w
        ICKc/eo8/OGyFvZPWNsLL2KjeVbb7+ccgE0Y41dmi9MYsNbBZ3DY9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T21:38:16Z"
  mac: ENC[AES256_GCM,data:n6wh0Rn/7zE6N2Nw5rBKZUXLXzKX0aSPM3wb0RyfkCotXyqr0/aicVQuVf5fv7q4Q0QQmFTeeTEL7HXl1tQQi6e9gs3p0sOc5iSzV4xHUs6YK1JYbaLNi7VxuupBhqTBXg/dyVjipXUl4HRK0AXL08lFwAz4aLZMsyiJ7UeKzpM=,iv:XtgkQzweBw9JpeCkII8A32C0MU78IhyVnBFNTKjBo0g=,tag:tiIdsCEE8t7XMGpo/Hw7hg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
